#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update


#Username validation ı kendimiz yapıyoruz. Ancak hibernate de bunu sonradan yaptığı için
#NullPointerException atıyor. Bunu önlemek için mode: none yapılıyor.
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
server:
  port: 8081

#spring security de log seviyesini arttırıyoruz(debug a çekiyoruz).
#logging:
#  level:
#    org.springframework: debug