#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update


#Username validation ı kendimiz yapıyoruz. Ancak hibernate de bunu sonradan yaptığı için
#NullPointerException atıyor. Bunu önlemek için mode: none yapılıyor.
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

##VIEW anotasyonundaki classlarda sorun çıkarmaması için kullanıldı.
#  jackson:
#    mapper:
#      DEFAULT_VIEW_INCLUSION: true



server:
  port: 8080

#spring security de log seviyesini arttırıyoruz(debug a çekiyoruz).
#logging:
#  level:
#    org.springframework: debug
