#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update


#Username validation ı kendimiz yapıyoruz. Ancak hibernate de bunu sonradan yaptığı için
#NullPointerException atıyor. Bunu önlemek için mode: none yapılıyor.
spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active: prod
hoaxify:
  upload-path: picture-storage

---
spring:
  profiles: prod
hoaxify:
  upload-path: storage-prod
---
spring:
  profiles: dev
hoaxify:
  upload-path: storage-dev
---

